version: '3.7'
services:
  web:
    image: ruby:2.6.5
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    working_dir: /app
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle install && rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    image: mdillon/postgis:11
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=gps_tracker
      - POSTGRES_PASSWORD=gps_tracker
volumes:
  bundle_cache:
  pg_data:
